import { existsSync, readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, join } from 'node:path'

// ---------------------------------------------------------------------------
// scripts/gen-active-client.ts
// ---------------------------------------------------------------------------
// Reads ACTIVE_CLIENT and writes src/lib/active-client.generated.ts with a
// single static import of that client's manifest. This is the mechanism that
// makes each build single-client: the module graph can only ever see the one
// client folder named here, so no other client's code is bundled.
//
// Runs automatically before every dev/build (via dev.ts and the build:* scripts)
// and on postinstall/pretypecheck (defaulting to _template) so a fresh checkout
// always type-checks. The generated file is git-ignored — never edit it by hand.
//
// Usage: ACTIVE_CLIENT=portfolio tsx scripts/gen-active-client.ts
//        tsx scripts/gen-active-client.ts            (defaults to _template)
// ---------------------------------------------------------------------------

const root = resolve(__dirname, '..')
const DEFAULT_CLIENT = '_template'

const clientName = process.env.ACTIVE_CLIENT ?? DEFAULT_CLIENT

const clientDir = join(root, 'clients', clientName)
const entryFile = join(clientDir, 'index.ts')

function listClients(): string[] {
  return readdirSync(join(root, 'clients')).filter(
    (name) => !name.startsWith('.'),
  )
}

if (!existsSync(clientDir)) {
  console.error(`❌ Client folder not found: clients/${clientName}/`)
  console.error(`Available clients: ${listClients().join(', ')}`)
  process.exit(1)
}

if (!existsSync(entryFile)) {
  console.error(`❌ Client entry not found: clients/${clientName}/index.ts`)
  console.error(`Every client must export a ClientManifest from index.ts.`)
  process.exit(1)
}

const outPath = join(root, 'src', 'lib', 'active-client.generated.ts')

const contents = `// AUTO-GENERATED by scripts/gen-active-client.ts — DO NOT EDIT.
// Regenerated before every dev/build and on postinstall. Git-ignored.
// Active client: ${clientName}
/* eslint-disable */
import { manifest } from '../../clients/${clientName}'
import type { ClientManifest } from '@/types/config'

export const activeClient: ClientManifest = manifest
`

// Avoid a no-op write (keeps file mtime stable, friendlier to watchers).
const existing = existsSync(outPath) ? readFileSync(outPath, 'utf-8') : ''
if (existing !== contents) {
  writeFileSync(outPath, contents, 'utf-8')
}

console.log(`✅ active-client.generated.ts → ${clientName}`)
